export const ADD_WORD = "ADD_WORD";
export const LOAD_WORDS = {
    START_FETCH: "LOAD_WORD_START_FETCH",
    FAIL_FETCH: "LOAD_WORD_FAIL_FETCH",
    FINISH_FETCH: "LOAD_WORD_FINISH_FETCH"
};

export const FLIP_FLASHCARD = "FLIP_FLASHCARD";